@startuml
!theme C4_sandstone from <C4/themes>
!include Templates/C4_Context.puml
title "Context diagrams: Тёплый дом"

SHOW_PERSON_OUTLINE()
' LAYOUT_LANDSCAPE()
LAYOUT_TOP_DOWN()
'LAYOUT_AS_SKETCH()

Person(user, "User", "Пользователь")
System(smart_house_system, "Smart house System ", "Система управления умным домом")

Boundary(house, "Дом") {
    System_Ext(heating_sensor_api, "Heating sensor API", "Внешний API для управления датчиком отопления",)
    System_Ext(temperature_sensor_api, "Temperature sensor API", "Внешний API для получения данных датчика температуры",)
}

Person_Ext(service_man, "Serviceman", "Наладчик")

Rel(user, smart_house_system, "Управляет отоплением в доме и проверяет температуру")
Rel(smart_house_system, heating_sensor_api, "Управляет")
Rel(smart_house_system, temperature_sensor_api, "Получает данные")

Rel(service_man, heating_sensor_api, "Устанавливает")
Rel(service_man, temperature_sensor_api, "Устанавливает")
@enduml