@startuml
!theme C4_sandstone from <C4/themes>
!include Templates/C4_Container.puml
title "Container diagrams: Тёплый дом"

SHOW_PERSON_OUTLINE()
' LAYOUT_LANDSCAPE()
' LAYOUT_AS_SKETCH()

Person(user, "User", "Пользователь")

Enterprise_Boundary(smart_house_system, "Smart Home (domen)") {

    Container(web_app, "Web Application", "", "Веб-приложение")  
    Container(api_gateway, "API Gateway", "Kong", "Маршрутизирует запросы к микросервисам")
           
    System_Boundary(sensor_management, "Sensor management (subdomen)") {
        Container(sensor_management_api_application, "API Application", "Go", "Предоставляет функции через API для управления датчиками")
        ContainerDb(sensor_management_database_service, "Database", "PostgreSQL", "Хранит информацию")
        
        Rel(sensor_management_api_application, sensor_management_database_service, "Читает и записывает")
    }

    System_Boundary(telemetry_management, "Telemetry management (subdomen)") {
        Container(telemetry_management_api_application, "API Application", "Go", "Предоставляет функции через API")
        Container(telemetry_management_sensor_api_monitor, "API Application", "Go", "API монитор датчиков")
        
        ContainerDb(telemetry_management_database_service, "Database", "NoSql", "Хранит информацию")
        ContainerQueue(queue, "Queue", "Очередь для высоконагруженных систем и потоковой обработки событий", "Apache Kafka")

        Rel(telemetry_management_api_application, telemetry_management_database_service, "Читает и записывает")
        Rel(telemetry_management_sensor_api_monitor, queue, "Публикует события от устройств")
        Rel(telemetry_management_api_application, queue, "Подписано на канал данных с информацией от устройств")
    }
   
    System_Boundary(user_management, "User management (subdomen)") {
        Container(user_management_api_application, "API Application", "Go", "Предоставляет функции через API")
        ContainerDb(user_management_database_service, "Database", "PostgreSQL", "Хранит информацию")

        Rel(user_management_api_application, user_management_database_service, "Читает и записывает")
    }

    System_Boundary(house_management, "Home management (subdomen)") {
        Container(house_management_api_application, "API Application", "Go", "Предоставляет функции через API")
        ContainerDb(house_management_database_service, "Database", "PostgreSQL", "Хранит информацию")

        Rel(house_management_api_application, house_management_database_service, "Читает и записывает")
    }

    Rel(user, web_app, "Использует")
    Rel(web_app, api_gateway, "Использует")
    Rel(api_gateway, sensor_management_api_application, "Использует")
    Rel(api_gateway, telemetry_management_api_application, "Использует")
    Rel(api_gateway, user_management_api_application, "Использует")
    Rel(api_gateway, house_management_api_application, "Использует")
}
@enduml